steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
  - script: |
      git config --global user.email $BUILD_REQUESTEDFOREMAIL
      git config --global user.name "$BUILD_REQUESTEDFOR"
      git config --global --list
    name: gitConfig
    displayName: Configure git
