parameters:
- name : PackageAll
  displayName: Package all projects
  type: boolean
  default: false
- name: VersionPolicy
  displayName: Version Policy (only if "package all")
  default: '-'
- name : Verbose
  displayName: Enable Verbose logging
  type: boolean
  default: false

appendCommitMessageToRunName: false
name: ${{ variables['Build.Reason'] }} for ${{ variables['Build.SourceBranchName'] }}
pool:
  vmImage: 'ubuntu-latest'

# update triggers according to your needs
trigger:
  branches:
    include:
    - features/*
  paths:
    include:
    - spfx-apps
    - spfx-libraries

variables:
  - template: templates/variables.yml
    parameters:
      PackageAll: ${{ parameters.PackageAll }}
      VersionPolicy: ${{ parameters.VersionPolicy }}
      Verbose: ${{ parameters.Verbose }}

steps:
  - checkout: self
    persistCredentials: true
    # https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#remarks
    fetchDepth: 0

  - template: templates/prerequisites.yml
  - script: 'node common/scripts/install-run-rush.js install'
    displayName: 'Rush Install'
  - script: 'node common/scripts/install-run-rush.js build'
    displayName: 'Rush Build'

  - script: 'node common/scripts/install-run-rush.js dist:package ${{ variables.packageAll }} ${{ variables.prerelease }}
          ${{ variables.cmdPackage }} ${{ variables.cmdCopy }}
          ${{ variables.targetBranch }}
          ${{ variables.versionPolicy }} ${{ variables.verbose }}'
    displayName: 'Rush ${{ variables.packageCommand }}'
  #Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'SPFx'
    displayName: 'Publish Artifact: SPFx'
